In [ ]:
!pip install edgartools

In [ ]:
from edgar import set_identity

set_identity("Mahesh Ponnam mahimahesh6842@gmail.com")

In [ ]:
from edgar import Company

company = Company("AAPL")
filings = company.get_filings(form="10-K")
filing = filings.latest()
text = filing.text()

In [ ]:
print(text)

In [ ]:
from edgar import *

set_identity("Mahesh Ponnam yourrealemail@gmail.com")

company = Company("AAPL")

filings = company.get_filings(form="10-K").latest()

text_10k= filings.text()
print(filings)
print(text_10k[:5000])

In [ ]:
from edgar import Company, set_identity
from datetime import date
import pandas as pd

In [ ]:
def fetch_company_filings(ticker: str, forms=("10-K", "10-Q"), limit=5):
    company = Company(ticker)

    rows= []
    for form in forms:
        filings= company.get_filings(form=form).head(limit)

        for filing in filings:
            rows.append({
                "ticker": ticker,
                "company": filing.company,
                "form_type": form,
                "filing_date": filing.filing_date,
                "accession_number": filing.accession_number,
                "text": filing.text()
            })

        return pd.DataFrame(rows)

In [ ]:

df = fetch_company_filings("AAPL", limit=2)
print(df.head())

In [ ]:
df.text[0][:500]

## Spliting text into sections

    - Item 1: business_context
    - Item 1A: risk_disclosure
    - Item 1C: cybersecurity_risk
    - Item 3: legal_regulatory_risk
    - Item 7: management_discussion_analysis
    - Item 7A: market_risk
    - Item 8: financial_statements

In [26]:
from edgar import *

set_identity("Mahesh Ponnam yourrealemail@gmail.com")

company = Company("AAPL")
filing = company.get_filings(form="10-K").latest()

tenk = filing.obj()

tenk

╭──────────────────────────────────────────────── Apple Inc. 10-K ────────────────────────────────────────────────╮
│ Period ending September 27, 2025 filed on October 31, 2025                                                      │
│                                                                                                                 │
│                                                                                                                 │
│ 📄                                                                                                              │
│ ├── PART I                                                                                                      │
│ │   ├── Item 1  Business                                                                                        │
│ │   ├── Item 1A Risk Factors                                                                                    │
│ │   ├── Item 1B Unresolved Staff Comments                                                                       │
│ │   ├── Item 1C Cybersecurity                                                                                   │
│ │   ├── Item 2  Properties                                                                                      │
│ │   ├── Item 3  Legal Proceedings                                                                               │
│ │   └── Item 4  Mine Safety Disclosures                                                                         │
│ ├── PART II                                                                                                     │
│ │   ├── Item 5  Market for Registrant's Common Equity                                                           │
│ │   ├── Item 6  Selected Financial Data                                                                         │
│ │   ├── Item 7  Management's Discussion and Analysis (MD&A)                                                     │
│ │   ├── Item 7A Quantitative and Qualitative Disclosures About Market Risk                                      │
│ │   ├── Item 8  Financial Statements                                                                            │
│ │   ├── Item 9  Controls and Procedures                                                                         │
│ │   ├── Item 9A Controls and Procedures                                                                         │
│ │   ├── Item 9B Other Information                                                                               │
│ │   └── Item 9C Disclosure Regarding Foreign Jurisdictions That Prevent Inspections                             │
│ ├── PART III                                                                                                    │
│ │   ├── Item 10 Directors, Executive Officers, and Corporate Governance                                         │
│ │   ├── Item 11 Executive Compensation                                                                          │
│ │   ├── Item 12 Security Ownership of Certain Beneficial Owners and Management                                  │
│ │   ├── Item 13 Certain Relationships and Related Transactions, and Director Independence                       │
│ │   └── Item 14 Principal Accounting Fees and Services                                                          │
│ └── PART IV                                                                                                     │
│     ├── Item 15 Exhibits, Financial Statement Schedules                                                         │
│     └── Item 16 Form 10-K Summary                                                                               │
│                                                                                                                 │
│                                                                                                                 │
│ ╭────────────────────────────────── 10-K Apple Inc. (AAPL) • CIK 0000320193 ──────────────────────────────────╮ │
│ │   Fiscal Period       Fiscal Year 2025 (ended Sep 27, 2025)                                                 │ │
│ │   Data                1,131 facts • 182 contexts                                                            │ │
│ │                                                                                                             │ │
│ │ Periods                                                                                                     │ │
│ │   Annual              FY 2025, FY 2024, FY 2023                                                             │ │
│ │   (1 future period after 2025-09-27 excluded)                                                               │ │
│ │                                                                                                             │ │
│ │ Statements (72)                                                                                             │ │
│ │   Statements        Income, Compr. Income, Balance Sheet, Equity, Cash Flow                                 │ │
│ │   Notes             Insider Trading Arrangements, Insider Trading Policies Proc, 9952165 - Disclosure - Deb │ │
│ │   Disclosures       Pvp Disclosure, Err Comp Disclosure, Award Timing Disclosure, 9955546 - Disclosure - De │ │
│ │   Document          0000001 - Document - Cover Page, 0000002 - Document - Audit or Information              │ │
│ ╰───────────────────────────────────────────────────────────────────── XBRL Data • xbrl.statements to browse ─╯ │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [27]:
dir(tenk)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rich__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_append_expands_with_values',
 '_cross_reference_index',
 '_filing',
 '_focused_context',
 '_parser',
 'auditor',
 'balance_sheet',
 'business',
 'cash_flow_statement',
 'chunked_document',
 'company',
 'directors_officers_and_governance',
 'doc',
 'document',
 'filing_date',
 'financials',
 'form',
 'get_item_with_part',
 'get_structure',
 'grep',
 'id_parse_document',
 'income_statement',
 'items',
 'management_discussion',
 'notes',
 'period_of_report',
 'reports',
 'risk_factors',
 'sections',
 'structure',
 'subsidiaries',
 'to_context',
 'view']

In [29]:
tenk.items

['Item 1',
 'Item 7A',
 'Item 8',
 'Item 9',
 'Item 9A',
 'Item 9B',
 'Item 9C',
 'Item 10',
 'Item 11',
 'Item 12',
 'Item 13',
 'Item 14',
 'Item 15',
 'Item 16',
 'Item 1A',
 'Item 1B',
 'Item 1C',
 'Item 2',
 'Item 3',
 'Item 4',
 'Item 5',
 'Item 6',
 'Item 7']

In [30]:
item_1a = tenk["Item 1A"]

print(item_1a[:5000])

Item 1A.    Risk Factors

The following summarizes factors that could have a material adverse effect on the Company’s business, reputation, results of operations, financial condition and stock price. The Company may not be able to accurately predict, control or mitigate these risks. Statements in this section are based on the Company’s beliefs and opinions regarding matters that could materially adversely affect the Company in the future and are not representations as to whether such matters have or have not occurred previously. The risks and uncertainties described below are not exhaustive and should not be considered a complete statement of all potential risks or uncertainties that the Company faces or may face in the future.

This section should be read in conjunction with Part II, Item 7, “Management’s Discussion and Analysis of Financial Condition and Results of Operations” and the consolidated financial statements and accompanying notes in Part II, Item 8, “Financial Statements and Supplementary Data” of this Form 10-K.

Macroeconomic and Industry Risks

The Company’s operations and performance depend significantly on global and regional economic conditions and adverse economic conditions can materially adversely affect the Company’s business, results of operations, financial condition and stock price.

The Company has international operations with sales outside the U.S. representing a majority of the Company’s total net sales. In addition, the Company’s global supply chain is large and complex and a majority of the Company’s supplier facilities, including manufacturing and assembly sites, are located outside the U.S. As a result, the Company’s operations and performance depend significantly on global and regional economic conditions.

Adverse macroeconomic conditions, including slow growth or recession, high unemployment, inflation, tighter credit, higher interest rates, and currency fluctuations, can adversely impact consumer confidence and spending and materially adversely affect demand for the Company’s products and services. In addition, consumer confidence and spending can be materially adversely affected in response to changes in fiscal and monetary policy, financial market volatility, declines in income or asset values, and other economic factors.

Uncertainty about, or a decline in, global or regional economic conditions can also have a significant impact on the Company’s suppliers, contract manufacturers, logistics providers, distributors, cellular network carriers and other channel partners, and developers. Potential outcomes include financial instability; inability to obtain credit to finance business operations; and insolvency.

Adverse economic conditions can also lead to increased credit and collectibility risk on the Company’s trade receivables; the failure of derivative counterparties and other financial institutions; limitations on the Company’s ability to issue new debt; reduced liquidity; and declines in the fair values of the Company’s financial instruments. These and other impacts can materially adversely affect the Company’s business, results of operations, financial condition and stock price.

Apple Inc. | 2025 Form 10-K | 5

The Company’s business can be impacted by political events, trade and other international disputes, geopolitical tensions, conflict, terrorism, natural disasters, public health issues, industrial accidents and other business interruptions.

Political events, trade and other international disputes, geopolitical tensions, conflict, terrorism, natural disasters, public health issues, industrial accidents and other business interruptions can have a material adverse effect on the Company and its customers, employees, suppliers, contract manufacturers, logistics providers, distributors, cellular network carriers and other channel partners.

The Company has a large, global business with sales outside the U.S. representing a majority of the Company’s total net sales, and the Company believes that it generally benefits from growth in international trade. A significant majority of the Company’s manufacturing is performed in whole or in part by outsourcing partners located primarily in China mainland, India, Japan, South Korea, Taiwan and Vietnam, in addition to sourcing from partners and facilities located in the U.S. Restrictions on international trade, such as tariffs and other controls on imports or exports of goods, technology or data, can materially adversely affect the Company’s business and supply chain. The impact can be particularly significant if these restrictive measures apply to countries and regions where the Company derives a significant portion of its revenues and/or has significant supply chain operations. Restrictive measures can increase the cost or limit the availability of the Company’s products and the components and rare earths and other raw materials that go into them. Restrictive measures can also require the Company to change suppliers, res

In [32]:
sections = {}

for item in tenk.items:
    try:
        section_text = tenk[item]
        sections[item] = section_text
        print(item, ":", len(section_text.split()), "words")
    except Exception as e:
        print(item, "failed:", e)

Item 1 : 2325 words
Item 7A : 451 words
Item 8 : 8491 words
Item 9 : 14 words
Item 9A : 649 words
Item 9B : 83 words
Item 9C : 352 words
Item 10 : 60 words
Item 11 : 284 words
Item 12 : 34 words
Item 13 : 30 words
Item 14 : 37 words
Item 15 : 1761 words
Item 16 : 316 words
Item 1A : 9782 words
Item 1B : 6 words
Item 1C : 370 words
Item 2 : 83 words
Item 3 : 830 words
Item 4 : 440 words
Item 5 : 404 words
Item 6 : 11 words
Item 7 : 2643 words

In [33]:
import pandas as pd

section_df = pd.DataFrame([
    {
        "item": item,
        "text": text,
        "word_count": len(text.split())
    }
    for item, text in sections.items()
])

section_df

       item                                               text  word_count
0    Item 1  Item 1.    Business\n\nCompany Background\n\nT...        2325
1   Item 7A  Item 7A.    Quantitative and Qualitative Discl...         451
2    Item 8  Item 8.    Financial Statements and Supplement...        8491
3    Item 9  Item 9.    Changes in and Disagreements with A...          14
4   Item 9A  Item 9A.    Controls and Procedures\n\nEvaluat...         649
5   Item 9B  Item 9B.    Other Information\n\nOn October 31...          83
6   Item 9C  Item 9C.    Disclosure Regarding Foreign Juris...         352
7   Item 10  Item 10.    Directors, Executive Officers and ...          60
8   Item 11  Item 11.    Executive CompensationThe informat...         284
9   Item 12  Item 12.    Security Ownership of Certain Bene...          34
10  Item 13  Item 13.    Certain Relationships and Related ...          30
11  Item 14  Item 14.    Principal Accountant Fees and Serv...          37
12  Item 15  Item 15.    Exhibit and Financial Statement Sc...        1761
13  Item 16  Item 16.    Form 10-K Summary\n\nNone.\n\nAppl...         316
14  Item 1A  Item 1A.    Risk Factors\n\nThe following summ...        9782
15  Item 1B     Item 1B.    Unresolved Staff Comments\n\nNone.           6
16  Item 1C  Item 1C.    Cybersecurity\n\nThe Company’s man...         370
17   Item 2  Item 2.    Properties\n\nThe Company’s headqua...          83
18   Item 3  Item 3.    Legal Proceedings\n\nDigital Market...         830
19   Item 4  Item 4.    Mine Safety DisclosuresNot applicab...         440
20   Item 5  Item 5.    Market for Registrant’s Common Equi...         404
21   Item 6  Item 6.    [Reserved]\n\nApple Inc. | 2025 For...          11
22   Item 7  Item 7.    Management’s Discussion and Analysi...        2643

In [35]:
import re

def clean_filing_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    # Replace non-breaking spaces
    text = text.replace("\xa0", " ")

    # Normalize smart quotes lightly
    text = text.replace("’", "'").replace("“", '"').replace("”", '"')

    # Add missing space between lowercase/period and uppercase words
    # Example: "DisclosuresNot applicable" -> "Disclosures Not applicable"
    text = re.sub(r"([a-z])([A-Z])", r"\1 \2", text)

    # Add space between period and next capital letter if missing
    # Example: "applicable.Item" -> "applicable. Item"
    text = re.sub(r"\.([A-Z])", r". \1", text)

    # Collapse repeated whitespace but keep text readable
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()

In [36]:
section_df["clean_text"] = section_df["text"].apply(clean_filing_text)
section_df["clean_word_count"] = section_df["clean_text"].apply(lambda x: len(x.split()))

# Real Section Names

In [39]:
ITEM_NAME_MAP = {
    "Item 1": "Business",
    "Item 1A": "Risk Factors",
    "Item 1B": "Unresolved Staff Comments",
    "Item 1C": "Cybersecurity",
    "Item 2": "Properties",
    "Item 3": "Legal Proceedings",
    "Item 4": "Mine Safety Disclosures",
    "Item 5": "Market for Registrant’s Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities",
    "Item 6": "Reserved",
    "Item 7": "Management’s Discussion and Analysis of Financial Condition and Results of Operations",
    "Item 7A": "Quantitative and Qualitative Disclosures About Market Risk",
    "Item 8": "Financial Statements and Supplementary Data",
    "Item 9": "Changes in and Disagreements with Accountants on Accounting and Financial Disclosure",
    "Item 9A": "Controls and Procedures",
    "Item 9B": "Other Information",
    "Item 9C": "Disclosure Regarding Foreign Jurisdictions that Prevent Inspections",
    "Item 10": "Directors, Executive Officers and Corporate Governance",
    "Item 11": "Executive Compensation",
    "Item 12": "Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters",
    "Item 13": "Certain Relationships and Related Transactions, and Director Independence",
    "Item 14": "Principal Accountant Fees and Services",
    "Item 15": "Exhibits and Financial Statement Schedules",
    "Item 16": "Form 10-K Summary"
}

In [41]:
CORE_SECTIONS = ["Item 1", "Item 1A", "Item 1C", "Item 3", "Item 7", "Item 7A", "Item 8"]

SECTION_USAGE = {
    "Item 1": "business_context",
    "Item 1A": "risk_disclosure",
    "Item 1C": "cybersecurity_risk",
    "Item 3": "legal_regulatory_risk",
    "Item 7": "management_discussion_analysis",
    "Item 7A": "market_risk",
    "Item 8": "financial_statements"
}

section_df["section_name"] = section_df["item"].map(ITEM_NAME_MAP)
section_df["use_for_modeling"] = section_df["item"].isin(CORE_SECTIONS)
section_df["section_usage"] = section_df["item"].map(SECTION_USAGE).fillna("metadata_or_reference")

In [43]:
section_df = section_df[
    [
        "item",
        "section_name",
        "section_usage",
        "use_for_modeling",
        "clean_text",
        "clean_word_count"
    ]
]

section_df.head(3)

,item,section_name,section_usage,use_for_modeling,clean_text,clean_word_count
0,Item 1,Business,business_context,True,Item 1. Business\n\nCompany Background\n\nThe ...,2359
1,Item 7A,Quantitative and Qualitative Disclosures About...,market_risk,True,Item 7A. Quantitative and Qualitative Disclosu...,457
2,Item 8,Financial Statements and Supplementary Data,financial_statements,True,Item 8. Financial Statements and Supplementary...,8580

In [44]:
core_section_df = section_df[section_df["use_for_modeling"] == True].copy()

core_section_df

,item,section_name,section_usage,use_for_modeling,clean_text,clean_word_count
0,Item 1,Business,business_context,True,Item 1. Business\n\nCompany Background\n\nThe ...,2359
1,Item 7A,Quantitative and Qualitative Disclosures About...,market_risk,True,Item 7A. Quantitative and Qualitative Disclosu...,457
2,Item 8,Financial Statements and Supplementary Data,financial_statements,True,Item 8. Financial Statements and Supplementary...,8580
14,Item 1A,Risk Factors,risk_disclosure,True,Item 1A. Risk Factors\n\nThe following summari...,9829
16,Item 1C,Cybersecurity,cybersecurity_risk,True,Item 1C. Cybersecurity\n\nThe Company's manage...,370
18,Item 3,Legal Proceedings,legal_regulatory_risk,True,Item 3. Legal Proceedings\n\nDigital Markets A...,841
22,Item 7,Management’s Discussion and Analysis of Financ...,management_discussion_analysis,True,Item 7. Management's Discussion and Analysis o...,2688

* I initially explored direct SEC API ingestion, but used EdgarTools for more reliable filing retrieval and section-level extraction. The pipeline stores raw filing text, extracts standardized filing sections, cleans the text, and prepares core sections for ESG NLP modeling.

In [45]:
from datetime import datetime, timezone

# Add filing-level metadata to existing section_df
section_df["issuer_id"] = "AAPL"
section_df["ticker"] = "AAPL"
section_df["cik"] = "0000320193"
section_df["company_name"] = "Apple Inc."
section_df["form_type"] = filing.form
section_df["filing_date"] = filing.filing_date
section_df["accession_number"] = filing.accession_number
section_df["ingested_at"] = datetime.now(timezone.utc).isoformat()

# Reorder columns
section_df = section_df[
    [
        "issuer_id",
        "ticker",
        "cik",
        "company_name",
        "form_type",
        "filing_date",
        "accession_number",
        "item",
        "section_name",
        "section_usage",
        "use_for_modeling",
        "clean_text",
        "clean_word_count",
        "ingested_at"
    ]
]

section_df.head()

,issuer_id,ticker,cik,company_name,form_type,filing_date,accession_number,item,section_name,section_usage,use_for_modeling,clean_text,clean_word_count,ingested_at
0,AAPL,AAPL,0000320193,Apple Inc.,10-K,2025-10-31,0000320193-25-000079,Item 1,Business,business_context,True,Item 1. Business\n\nCompany Background\n\nThe ...,2359,2026-05-09T18:01:49.366821+00:00
1,AAPL,AAPL,0000320193,Apple Inc.,10-K,2025-10-31,0000320193-25-000079,Item 7A,Quantitative and Qualitative Disclosures About...,market_risk,True,Item 7A. Quantitative and Qualitative Disclosu...,457,2026-05-09T18:01:49.366821+00:00
2,AAPL,AAPL,0000320193,Apple Inc.,10-K,2025-10-31,0000320193-25-000079,Item 8,Financial Statements and Supplementary Data,financial_statements,True,Item 8. Financial Statements and Supplementary...,8580,2026-05-09T18:01:49.366821+00:00
3,AAPL,AAPL,0000320193,Apple Inc.,10-K,2025-10-31,0000320193-25-000079,Item 9,Changes in and Disagreements with Accountants ...,metadata_or_reference,False,Item 9. Changes in and Disagreements with Acco...,14,2026-05-09T18:01:49.366821+00:00
4,AAPL,AAPL,0000320193,Apple Inc.,10-K,2025-10-31,0000320193-25-000079,Item 9A,Controls and Procedures,metadata_or_reference,False,Item 9A. Controls and Procedures\n\nEvaluation...,649,2026-05-09T18:01:49.366821+00:00